#!/bin/sh -e

. /etc/os-release
SOURCE_LIST="/etc/apt/sources.list.d/nlnetlabs.list"

create_sources_list() {
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/nlnetlabs-archive-keyring.gpg] https://packages.nlnetlabs.nl/linux/${ID} ${VERSION_CODENAME} main" > ${SOURCE_LIST}
}

case "$1" in
configure)
    create_sources_list
    ;;
esac

#DEBHELPER#

